modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
disable_current_tag_swap = true

# Specific programs
[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "kitty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "rofi -show run"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "Execute"
value = "discord"
modifier = ["modkey","Control"]
key = "d"

# Screenshot
[[keybind]]
command = "Execute"
value = "maim -u ~/Images/$(date +%s).png"
modifier = []
key = "Print"

[[keybind]]
command = "Execute"
value = "maim -su | xclip -selection clipboard -t image/png"
modifier = ["Shift"]
key = "Print"


[[keybind]]
command = "Execute"
value = "maim -su ~/Images/$(date +%s)_w.png"
modifier = ["Control"]
key = "Print"

# Volume control keys
[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ +5%"
modifier = []
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
modifier = []
key = "XF86XK_AudioMute"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ -5%"
modifier = []
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
modifier = []
key = "XF86XK_AudioMicMute"

# Backlight control keys
[[keybind]]
command = "Execute"
value = "xbacklight -inc 5"
modifier = []
key = "XF86XK_MonBrightnessUp"

[[keybind]]
command = "Execute"
value = "xbacklight -dec 5"
modifier = []
key = "XF86XK_MonBrightnessDown"

# Window and tag control
[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "i3lock -k --timecolor=deadbeef --datecolor=deadbeef --pass-volume-keys -i Images/cameron-venti.png"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey","Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "ampersand"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "eacute"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "quotedbl"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "apostrophe"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "parenleft"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "minus"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "egrave"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "underscore"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "ccedilla"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "ampersand"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "eacute"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "quotedbl"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "apostrophe"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "parenleft"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "minus"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "egrave"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "underscore"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "ccedilla"
